[2025-01-29T23:39:37.533+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spotify_etl.load_task scheduled__2025-01-12T00:00:00+00:00 [queued]>
[2025-01-29T23:39:37.568+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spotify_etl.load_task scheduled__2025-01-12T00:00:00+00:00 [queued]>
[2025-01-29T23:39:37.572+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-01-29T23:39:37.661+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): load_task> on 2025-01-12 00:00:00+00:00
[2025-01-29T23:39:37.712+0000] {standard_task_runner.py:60} INFO - Started process 109 to run task
[2025-01-29T23:39:37.727+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'spotify_etl', 'load_task', 'scheduled__2025-01-12T00:00:00+00:00', '--job-id', '50', '--raw', '--subdir', 'DAGS_FOLDER/spotify_etl_dag.py', '--cfg-path', '/tmp/tmpxjjplsis']
[2025-01-29T23:39:37.754+0000] {standard_task_runner.py:88} INFO - Job 50: Subtask load_task
[2025-01-29T23:39:38.023+0000] {task_command.py:423} INFO - Running <TaskInstance: spotify_etl.load_task scheduled__2025-01-12T00:00:00+00:00 [running]> on host d9ce99263c32
[2025-01-29T23:39:38.513+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='spotify_etl' AIRFLOW_CTX_TASK_ID='load_task' AIRFLOW_CTX_EXECUTION_DATE='2025-01-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-12T00:00:00+00:00'
[2025-01-29T23:39:38.528+0000] {spotify_etl_dag.py:70} INFO - Starting load process...
[2025-01-29T23:39:38.555+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:315: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(k, replacements))

[2025-01-29T23:39:38.585+0000] {logging_mixin.py:188} INFO - Load task started at: 2025-01-12 00:00:00+00:00
[2025-01-29T23:39:38.666+0000] {logging_mixin.py:188} INFO - Retrieved 4 songs from XCom
[2025-01-29T23:39:38.673+0000] {logging_mixin.py:188} INFO - Retrieved 4 albums from XCom
[2025-01-29T23:39:38.734+0000] {base.py:83} INFO - Using connection ID 'mysql_connection' for task execution.
[2025-01-29T23:40:00.340+0000] {load.py:99} ERROR - Error loading data: (2002, "Can't connect to server on 'database-1.c1eo8uma67by.us-east-2.rds.amazonaws.com' (115)")
[2025-01-29T23:40:00.362+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/spotify_etl_dag.py", line 82, in load
    load_to_staging(songs, albums)
  File "/opt/airflow/dags/etl/load.py", line 62, in load_to_staging
    create_schemas_if_not_exist(mysql_hook)
  File "/opt/airflow/dags/etl/load.py", line 10, in create_schemas_if_not_exist
    connection = mysql_hook.get_conn()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/mysql/hooks/mysql.py", line 195, in get_conn
    return MySQLdb.connect(**conn_config)
  File "/home/airflow/.local/lib/python3.8/site-packages/MySQLdb/__init__.py", line 121, in Connect
    return Connection(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/MySQLdb/connections.py", line 193, in __init__
    super().__init__(*args, **kwargs2)
MySQLdb.OperationalError: (2002, "Can't connect to server on 'database-1.c1eo8uma67by.us-east-2.rds.amazonaws.com' (115)")
[2025-01-29T23:40:00.480+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=spotify_etl, task_id=load_task, execution_date=20250112T000000, start_date=20250129T233937, end_date=20250129T234000
[2025-01-29T23:40:00.527+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 50 for task load_task ((2002, "Can't connect to server on 'database-1.c1eo8uma67by.us-east-2.rds.amazonaws.com' (115)"); 109)
[2025-01-29T23:40:00.567+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-01-29T23:40:00.610+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
