[2024-12-19T03:43:45.844+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: test_library_import.test_imports manual__2024-12-19T03:43:45.188306+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
